#!/usr/bin/python3

import nmap

# Atronix IT and Solutions - Nmap Scanner Automated by Gazi Sadman Sharier Tanim  2133433

scanner = nmap.PortScanner()

print("Welcome, this is a simple nmap automation tool")
print("<----------------------------------------------------->")

ip_addr = input("Please enter the IP address you want to scan: ")
print("The IP you entered is: ", ip_addr)
type(ip_addr)

resp = input("""\nPlease enter the type of scan you want to run
                1) SYN ACK Scan
                2) UDP Scan
                3) Comprehensive Scan \n""")
print("You have selected option: ", resp)

# Dictionary of scan options
resp_dict = {
    '1': ['-v -sS', 'tcp'],
    '2': ['-v -sU', 'udp'],
    '3': ['-v -sS -sV -sC -A -O', 'tcp']
}

if resp not in resp_dict.keys():
    print("Please enter a valid option")
else:
    print("nmap version: ", scanner.nmap_version())
    scanner.scan(ip_addr, "1-1024", resp_dict[resp][0])  # Port range to scan, last part is the scan type
    print(scanner.scaninfo())
    if scanner[ip_addr].state() == 'up':
        print("Scanner Status: ", scanner[ip_addr].state())
        print("Protocols: ", scanner[ip_addr].all_protocols())
        print("Open Ports: ", scanner[ip_addr][resp_dict[resp][1]].keys())  # Display all open ports
